[package]
name = "pq-stealth-ethereum"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
alloy = { workspace = true, features = ["consensus", "consensus-secp256k1", "eips", "k256", "network", "signer-local", "sol-types"] }
alloy-sol-types.workspace = true
pq-stealth.workspace = true
serde.workspace = true
thiserror.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom-02.workspace = true

[lints]
workspace = true
